// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVB9RggdPZFwrir_ke0eXxCY4U28ulPaU',
    appId: '1:399645072614:web:21b827966d67b630ddaf27',
    messagingSenderId: '399645072614',
    projectId: 'fir-e50da',
    authDomain: 'fir-e50da.firebaseapp.com',
    storageBucket: 'fir-e50da.firebasestorage.app',
    measurementId: 'G-2S6PDGPB4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6J-MQB67wXiWuiO3HKYBRhBfD4LRJQJI',
    appId: '1:399645072614:android:55f101c49ce87a9dddaf27',
    messagingSenderId: '399645072614',
    projectId: 'fir-e50da',
    storageBucket: 'fir-e50da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU0z8zh1LKCw8c5ihHuaiKAo0cWR4UGi8',
    appId: '1:399645072614:ios:307a3781fd01d599ddaf27',
    messagingSenderId: '399645072614',
    projectId: 'fir-e50da',
    storageBucket: 'fir-e50da.firebasestorage.app',
    iosBundleId: 'com.example.dhakaBusRouteFare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU0z8zh1LKCw8c5ihHuaiKAo0cWR4UGi8',
    appId: '1:399645072614:ios:307a3781fd01d599ddaf27',
    messagingSenderId: '399645072614',
    projectId: 'fir-e50da',
    storageBucket: 'fir-e50da.firebasestorage.app',
    iosBundleId: 'com.example.dhakaBusRouteFare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVB9RggdPZFwrir_ke0eXxCY4U28ulPaU',
    appId: '1:399645072614:web:5ee3998c1fa80379ddaf27',
    messagingSenderId: '399645072614',
    projectId: 'fir-e50da',
    authDomain: 'fir-e50da.firebaseapp.com',
    storageBucket: 'fir-e50da.firebasestorage.app',
    measurementId: 'G-R12KZ8SGWE',
  );
}
