// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMuJikzYc_CacW1eKzquiKsu38bSoES8o',
    appId: '1:962799677345:web:2ac488e1496d5ddb8d65e0',
    messagingSenderId: '962799677345',
    projectId: 'bushub-6b935',
    authDomain: 'bushub-6b935.firebaseapp.com',
    storageBucket: 'bushub-6b935.firebasestorage.app',
    measurementId: 'G-630H3JHX7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAoLGsQPzlJeFousTDI8x14GNhqwx_afU',
    appId: '1:962799677345:android:eb7dda39f0dac6938d65e0',
    messagingSenderId: '962799677345',
    projectId: 'bushub-6b935',
    storageBucket: 'bushub-6b935.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSh_cJWQ1usBBLxbGJdlWAsW82GekfugE',
    appId: '1:962799677345:ios:5a463aedfedd22188d65e0',
    messagingSenderId: '962799677345',
    projectId: 'bushub-6b935',
    storageBucket: 'bushub-6b935.firebasestorage.app',
    iosBundleId: 'com.example.bushub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSh_cJWQ1usBBLxbGJdlWAsW82GekfugE',
    appId: '1:962799677345:ios:5a463aedfedd22188d65e0',
    messagingSenderId: '962799677345',
    projectId: 'bushub-6b935',
    storageBucket: 'bushub-6b935.firebasestorage.app',
    iosBundleId: 'com.example.bushub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMuJikzYc_CacW1eKzquiKsu38bSoES8o',
    appId: '1:962799677345:web:d1d94c150188994e8d65e0',
    messagingSenderId: '962799677345',
    projectId: 'bushub-6b935',
    authDomain: 'bushub-6b935.firebaseapp.com',
    storageBucket: 'bushub-6b935.firebasestorage.app',
    measurementId: 'G-SK31BDPE9W',
  );
}
